/// Holds the calculated cognitive indices and adaptive metrics
/// generated by the AI/ML performance analysis module.
class CognitiveScore {
  final double overallScore; // 0 - 100
  final double memoryIndex; // 0 - 100
  final double attentionIndex; // 0 - 100
  final double sequenceIndex; // 0 - 100
  final double patternIndex; // 0 - 100
  final double processingSpeedIndex; // 0 - 100
  final int totalSessions;
  final int currentStreakDays;
  final String statusNote;
  final DateTime lastUpdated;

  CognitiveScore({
    required this.overallScore,
    required this.memoryIndex,
    required this.attentionIndex,
    required this.sequenceIndex,
    required this.patternIndex,
    required this.processingSpeedIndex,
    required this.totalSessions,
    required this.currentStreakDays,
    required this.statusNote,
    required this.lastUpdated,
  });

  factory CognitiveScore.initial() {
    return CognitiveScore(
      overallScore: 0.0,
      memoryIndex: 0.0,
      attentionIndex: 0.0,
      sequenceIndex: 0.0,
      patternIndex: 0.0,
      processingSpeedIndex: 0.0,
      totalSessions: 0,
      currentStreakDays: 0,
      statusNote: 'New Profile — Play a game to start tracking!',
      lastUpdated: DateTime.now(),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'overallScore': overallScore,
      'memoryIndex': memoryIndex,
      'attentionIndex': attentionIndex,
      'sequenceIndex': sequenceIndex,
      'patternIndex': patternIndex,
      'processingSpeedIndex': processingSpeedIndex,
      'totalSessions': totalSessions,
      'currentStreakDays': currentStreakDays,
      'statusNote': statusNote,
      'lastUpdated': lastUpdated.toIso8601String(),
    };
  }

  factory CognitiveScore.fromMap(Map<String, dynamic> map) {
    return CognitiveScore(
      overallScore: (map['overallScore'] as num?)?.toDouble() ?? 0.0,
      memoryIndex: (map['memoryIndex'] as num?)?.toDouble() ?? 0.0,
      attentionIndex: (map['attentionIndex'] as num?)?.toDouble() ?? 0.0,
      sequenceIndex: (map['sequenceIndex'] as num?)?.toDouble() ?? 0.0,
      patternIndex: (map['patternIndex'] as num?)?.toDouble() ?? 0.0,
      processingSpeedIndex: (map['processingSpeedIndex'] as num?)?.toDouble() ?? 0.0,
      totalSessions: map['totalSessions'] ?? 0,
      currentStreakDays: map['currentStreakDays'] ?? 0,
      statusNote: map['statusNote'] ?? 'New Profile — Play a game to start tracking!',
      lastUpdated: map['lastUpdated'] != null
          ? DateTime.tryParse(map['lastUpdated']) ?? DateTime.now()
          : DateTime.now(),
    );
  }
}
